apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: administrationservice
  namespace: emigrate-dev-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: administrationservice
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
