apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reportservice
  namespace: emigrate-dev-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reportservice
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
